---
title: "Datos de felinos de Costa Rica"
author: "Daniela Castro Rivera"
date: '2022-06-08'
output:
html_document:
code_folding: hide
theme: readable
toc: true
toc_depth: 5
toc_float:
collapsed: false
smooth_scroll: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Carga de paquetes de R 

```{r carga-paquetes, message=FALSE}
# Carga de paquetes de R 
library(dplyr)
library(ggplot2) 
library(plotly) 
library(DT) 
library(sf) 
library(terra) 
library(raster) 
library(leaflet) 
```

```{r, include=FALSE}
felinos <-
  st_read(
    "C:/Users/gf0604-1/Practica Git/felinos.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude", # columna de longitud decimal
      "Y_POSSIBLE_NAMES=decimalLatitude"   # columna de latitud decimal
    ),
    quiet = TRUE
  )
```

# Visualizaciones de datos
## Tablas
### Registros de presencia

```{r Tabla, }
# Visualización de datos de felinos en formato tabular
felinos %>%
  st_drop_geometry() %>% # se suprime la columna de geometría
  dplyr::select(species,
                # selección de columnas
                eventDate,
                stateProvince,
                locality,
                decimalLongitude,
                decimalLatitude) %>%
  datatable(
    options = list(
      pageLength = 5,
      # cantidad de registros en una página
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json') # traducción al español
    ),
    colnames = c(
      # encabezados de las columnas
      "Especie",
      "Fecha",
      "Provincia",
      "Localidad",
      "Longitud",
      "Latitud"
    )
  )
```


#Graficos 

## Registros de presencia por especie
```{r grafico}
graficos_barras <-
  felinos %>%
  ggplot(aes(x = species)) +
  geom_bar() 
ggplotly(graficos_barras)

```

# Mapa

## Registros de presencia
```{r mapa, massage=FALSE}
leaflet() %>%
  addTiles() %>% 
  addCircleMarkers( 
    data = felinos,
    stroke = F,
    radius = 4,
    fillColor = 'blue',
    fillOpacity = 1
  )
```

